arthurdach/rbnb

- app/controllers/materials_controller.rb
- app/controllers/pages_controller.rb
- app/views/materials/show.html.erb
- app/views/pages/home.html.erb
- config/routes.rb
- db/seeds.rb
- test/controllers/materials_controller_test.rb
> Book material

- app/controllers/locations_controller.rb
- app/views/locations/new.html.erb
- config/routes.rb
- test/controllers/locations_controller_test.rb
@mctinmar @vincentbirgand @Thibaut92 Guys please review, thanks
> Locations en cours et formulaire-step3

- app/controllers/materials_controller.rb
- app/views/materials/_form.html.erb
- app/views/materials/edit.html.erb
- app/views/materials/index.html.erb
- app/views/materials/new.html.erb
- app/views/materials/show.html.erb
- db/seeds.rb
> ajouter materiel

- app/models/material.rb
- app/models/type.rb
- app/models/user.rb
- db/migrate/20181127143739_drop_types_table.rb
- db/migrate/20181127145810_drop_types.rb
- db/migrate/20181127145958_add_name_and_category_to_materials.rb
- db/schema.rb
- db/seeds.rb
@mctinmar @vincentbirgand @Thibaut92 les copaints regardez les trois dernières migrations et le ficher de seeds.
PS: j'ai aussi mis à jour les associations entre les modèles
> migration to drop types table and update material table + seeds update

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_form.scss
- app/assets/stylesheets/components/_index.scss
- app/views/locations/index.html.erb
- app/views/locations/new.html.erb
- app/views/locations/validation.html.erb
- app/views/pages/home.html.erb
@mctinmar @vincentbirgand @Thibaut92 
Please check this awesome style + divs and components (banner / card / form)
thanks
> divs + components + style pages

- app/controllers/materials_controller.rb
- app/policies/material_policy.rb
- app/views/materials/index.html.erb
changement confg pudit sur material controller vue et policy
@mctinmar @vincentbirgand @arthurdach
> pundit config sur controller material, vue et policy

- app/controllers/pages_controller.rb
- app/policies/application_policy.rb
- app/policies/material_policy.rb
- app/views/layouts/application.html.erb
- app/views/materials/index.html.erb
@vincentbirgand @mctinmar @Thibaut92 
Pundit Okay
> policies pundit done

- app/controllers/pages_controller.rb
- app/views/layouts/application.html.erb
- app/views/materials/show.html.erb
- app/views/shared/_flashes.html.erb
> pundit material  done + alert enlevé + homepage done

- app/controllers/materials_controller.rb
- app/models/material.rb
- app/views/materials/_form.html.erb
- app/views/materials/show.html.erb
> finalisation cloudinary

- app/assets/stylesheets/components/_homeform.scss
- app/assets/stylesheets/components/_index.scss
- app/views/pages/home.html.erb
@Thibaut92 @arthurdach @vincentbirgand 
yooyoyo
> Front homepage

- .gitignore
- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_home.scss
- app/assets/stylesheets/components/_homeform.scss
- app/assets/stylesheets/components/_index.scss
- app/views/materials/edit.html.erb
- app/views/materials/new.html.erb
- app/views/pages/home.html.erb
> front page

- db/seeds.rb
modif seed 
@vincentbirgand @arthurdach @Thibaut92
> modif seed

- app/views/pages/home.html.erb
> photo front + seeds

- app/views/materials/index.html.erb
> card index

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_rating.scss
- app/controllers/material_reviews_controller.rb
- app/controllers/materials_controller.rb
- app/models/material.rb
- app/models/material_review.rb
- app/policies/material_review_policy.rb
- app/views/material_reviews/create.html.erb
- app/views/material_reviews/destroy.html.erb
- app/views/material_reviews/index.html.erb
- app/views/material_reviews/new.html.erb
- app/views/material_reviews/show.html.erb
- app/views/materials/show.html.erb
- config/routes.rb
- db/migrate/20181129105911_create_material_reviews.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/material_reviews_controller_test.rb
- test/models/material_review_test.rb
- test/policies/material_review_policy_test.rb
@vincentbirgand @mctinmar @Thibaut92  
Si vous pouvez checker et merge please, thks
> Add reviews

- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
- app/views/locations/new.html.erb
- package.json
- yarn.lock
@mctinmar @arthurdach @Thibaut92 
date picker ok
> date picker ok

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_home.scss
- app/views/materials/index.html.erb
- app/views/pages/home.html.erb
cards propre / page index / bouton louer votre matériel fix / footer en home
> front index home

- app/assets/stylesheets/components/_banner.scss
- app/views/locations/index.html.erb
- app/views/locations/new.html.erb
- app/views/material_reviews/new.html.erb
- app/views/materials/new.html.erb
> material new, material review, location index, location new

- app/assets/stylesheets/components/_card.scss
- app/views/materials/index.html.erb
- app/views/pages/home.html.erb
> cards mon materiel

- app/assets/stylesheets/components/_card.scss
- app/views/pages/home.html.erb
> card home ok

- app/controllers/pages_controller.rb
- app/views/pages/home.html.erb
ajout de la map pour la recheche
> ajout de la carte lors d une recherche sur la home

- app/assets/stylesheets/components/_banner.scss
- app/assets/stylesheets/components/_card.scss
- app/views/materials/index.html.erb
- app/views/materials/new.html.erb
- app/views/materials/show.html.erb
@vincentbirgand  @arthurdach @Thibaut92 
yo
> fix banner footer show index

- app/assets/stylesheets/components/_card.scss
- app/assets/stylesheets/components/_home.scss
- app/views/materials/show.html.erb
- app/views/pages/home.html.erb
home fixe + title show materiel
> Front final part

- app/views/materials/show.html.erb
> fixe image show material
